login: 
  azure_enabled: 
    default: false 
    client: true 
  azure_client_id: '' 
  azure_client_secret: '' 
  azure_title: '' 
    default: 'Azure AD' 
    client: true 
  azure_button_title: 
    default: 'with Azure AD' 
    client: true 